### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lungustefan** [mathewalves/Proxmox-Debian12#1]
The script get's stuck at starting download:
![Screenshot_20240421_115920_Termius](https://github.com/mathewalves/Proxmox-Debian12/assets/154420615/7358d7b2-d62a-4da2-9966-c5750c846bfe)

**Comment by mathewalves** [comment]
Hi, could you give me more information about the distro you are using?

**Comment by lungustefan** [comment]
Debian 12 default

**Comment by aleixsr** [comment]
Hi, same issue here, it seems related to "nala!, can you please help?

**Comment by JeremieMercier** [comment]
Same thing here with Debian 12.

Solution: 

1. installing packages manually with the “apt install” command
2. If you have installed the "nala" package, then you need to uninstall it
3. And run the setup "./setup" again but this time no longer install the optional packages.
